name: qr_app
description: A Flutter QR Code app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  mobile_scanner: ^5.2.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
